spring:
  datasource:
    spring-example:
      url: jdbc:mysql://host.docker.internal:3306/spring-example?serverTimezone=UTC
      username: root
      password: 1191992Da
test:
  url: myPersonalUrl
