GET {{host}}/user/1
Content-Type: application/json
Accept: application/json

###

GET {{host}}/user?username=Stefania
Content-Type: application/json
Accept: application/json

###

POST {{host}}/user/save
Content-Type: application/json
Accept: application/json

{
  "user": {
    "username": "Test",
    "password": "password",
    "address": "Via Verdi 4D"
  }
}

###

GET {{host}}/products
Content-Type: application/json
Accept: application/json