GET {{localhost}}/user/4
Content-Type: application/json
Accept: application/json

###

GET {{localhost}}/user?username=Stefania
Content-Type: application/json
Accept: application/json

###

POST {{localhost}}/user/save
Content-Type: application/json
Accept: application/json

{
  "user": {
    "username": "Test",
    "password": "password",
    "address": "Via Verdi 4D"
  }
}

###

GET {{localhost}}/products
Content-Type: application/json
Accept: application/json