### Retrieve a user by id

GET {{host}}/api/user/1
Content-Type: application/json
Accept: application/json

### Retrieve a user by username

GET {{host}}/api/user?username=Test
Content-Type: application/json
Accept: application/json

### Save a new user

POST {{host}}/api/user/save
Content-Type: application/json
Accept: application/json

{
  "user": {
    "username": "Test",
    "password": "password",
    "address": "Via Verdi 4D"
  }
}

### Save a new order

POST {{host}}/api/saveOrder
Content-Type: application/json
Accept: application/json

{
  "username": "Davide",
  "order": {
    "type": "House"
  }
}

### Retrieve list of products

GET {{host}}/api/products
Content-Type: application/json
Accept: application/json