services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - spring-example1-data-prod:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  app:
    image: davide92/spring-example1
    container_name: app
    restart:
      always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USERNAME=root       #env var in your OS
      - MYSQL_PASSWORD=password   #env var in your OS
  external-catalog:
    image: davide92/external-catalog
    container_name: external-catalog
volumes:
  spring-example1-data-prod:
    driver: local