services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-test-data:/var/lib/mysql
  app:
    image: davide92/spring-example1
    container_name: app
    restart:
      always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
  external-catalog:
    image: davide92/external-catalog
    container_name: external-catalog
volumes:
  mysql-test-data:
    driver: local