services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
#  external-catalog:
#    image: davide92/external-catalog
#    ports:
#      - "8081:8080"