version: '3'
services:
  mysqldb:
    image: davide92/mysql-custom
    ports:
      - "3306:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
  external-catalog:
    image: davide92/external-catalog
    ports:
      - "8081:8080"
volumes:
  mysql-test-data:
    driver: local