spring:
  datasource:
    spring-example:
      url: jdbc:mysql://mysql:3306/spring-example?serverTimezone=UTC
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
test:
  url: myPersonalUrl

products:
  url: http://external-catalog:8080