spring:
  datasource:
    spring-example:
      url: jdbc:mysql://localhost:3306/spring-example?serverTimezone=UTC
      username: root
      password: password
  kafka:
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092

test:
  url: myPersonalUrl

products:
  url: http://localhost:8081
