server:
  servlet:
    context-path: /api

spring:
  datasource:
    spring-example:
      host: mysql
      port: 3306
      database: spring-example
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
test:
  url: myPersonalUrl

products:
  url: http://external-catalog:8080