spring:
  datasource:
    spring-example:
      url: jdbc:mysql://mysqldb:3306/spring-example?serverTimezone=UTC
      username: root
      password: password
  kafka:
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: host.docker.internal:9092
test:
  url: myPersonalUrl

products:
  url: http://external-catalog:8080